import { describe,it,expect } from 'vitest';
import { buildLineIndex,makeSpan } from '@flowguard/core';
import { applyEditorChanges,editorRange,markerData } from '../../src/editor/text.js';
import { createSnapshot,currentSnapshot } from '../../src/adapters/snapshot.js';
import { displayFilename,readSourceFile } from '../../src/adapters/files.js';
import { initialWorkspace,workspaceReducer } from '../../src/workspace/reducer.js';
describe('editor and file adapters',()=>{
 it('maps normalized editor ranges onto exact BOM/CRLF/CR/Unicode source',()=>{const source='\uFEFFprint("😀");\r\nprint("a");\rprint("b");';const next=applyEditorChanges(source,[{range:{startLineNumber:2,startColumn:8,endLineNumber:2,endColumn:9},text:'x'},{range:{startLineNumber:1,startColumn:8,endLineNumber:1,endColumn:10},text:'z'}]);expect(next).toBe('\uFEFFprint("z");\r\nprint("x");\rprint("b");');});
 it('keeps EOF and UTF-16 markers aligned, compensating for hidden BOM',()=>{const source='\uFEFFprint("😀");\r\n';const span=makeSpan(buildLineIndex(source),1,6);expect(editorRange(span,source)).toEqual({startLineNumber:1,startColumn:1,endLineNumber:1,endColumn:6});const eof=makeSpan(buildLineIndex(source),source.length,source.length);expect(markerData([{code:'PARSE_EXPECTED',stage:'parse',severity:'error',blocking:true,message:'Expected value',span:eof}],source)[0]).toMatchObject({startLineNumber:2,startColumn:1,endLineNumber:2,endColumn:1,severity:8});});
 it('hashes exact bytes and discards snapshots after revision changes',async()=>{const a=await createSnapshot('a\r\n','source.fg',3),b=await createSnapshot('a\n','source.fg',3);expect(a.sha256).not.toBe(b.sha256);expect(a.snapshotId).toBe(`snapshot-3-${a.sha256}`);expect(await currentSnapshot('a','source.fg',3,()=>4)).toBeNull();expect((await currentSnapshot('a','source.fg',3,()=>3))?.revision).toBe(3);});
 it('reads fatal UTF-8, preserves BOM/newlines, and rejects size before reading',async()=>{const fake=(bytes:Uint8Array)=>({name:'dir/test.fg',size:bytes.length,arrayBuffer:async()=>bytes.buffer}) as File;expect(await readSourceFile(fake(new TextEncoder().encode('\uFEFFx\r\n')))).toEqual({source:'\uFEFFx\r\n',filename:'test.fg'});await expect(readSourceFile(fake(new Uint8Array([255])))).rejects.toThrow('valid UTF-8');await expect(readSourceFile({size:262145,arrayBuffer:()=>{throw Error('must not read');}} as unknown as File)).rejects.toThrow('256 KiB');expect(displayFilename('C:\\folder\\x.fg')).toBe('x.fg');});
 it('clears dirty state only for the saved revision',()=>{const draft=workspaceReducer(initialWorkspace,{type:'EDIT_SOURCE',source:'print(1);'});expect(workspaceReducer(draft,{type:'SOURCE_SAVED',revision:0}).dirty).toBe(true);expect(workspaceReducer(draft,{type:'SOURCE_SAVED',revision:1}).dirty).toBe(false);});
});
