import { afterEach,describe,it,expect,vi } from 'vitest';
import { ExecutionClient } from '../../src/adapters/executionClient.js';
import { runBytecode, type ExecutionRequest } from '@flowguard/core';
import { emptyAnalysis } from '../../../../packages/core/test/fixtures.js';
class FakeWorker {onmessage:((event:{data:unknown})=>void)|null=null;onerror:(()=>void)|null=null;onmessageerror:(()=>void)|null=null;terminate=vi.fn();postMessage=vi.fn();send(data:unknown){this.onmessage?.({data});}}
const request=(id='run-1'):ExecutionRequest=>{const a=emptyAnalysis();return {type:'execute',protocolVersion:1,requestId:id,snapshotId:a.snapshot!.snapshotId,revision:0,bytecode:a.artifacts.bytecode!,inputs:[]};};
afterEach(()=>vi.useRealTimers());
describe('separate one-shot execution transport',()=>{
 it('ignores identity mismatches and duplicate results',()=>{const w=new FakeWorker(),result=vi.fn(),client=new ExecutionClient(result,()=>w as unknown as Worker),r=request(),terminal=runBytecode(r,{nowMs:()=>0});client.start(r);w.send({...terminal,requestId:'other'});w.send({...terminal,revision:1});w.send({...terminal,snapshotId:'other'});expect(result).not.toHaveBeenCalled();w.send(terminal);w.send(terminal);expect(result).toHaveBeenCalledExactlyOnceWith(terminal);expect(w.terminate).toHaveBeenCalledOnce();});
 it('terminates Stop, starts fresh, and rejects a retired worker',()=>{const a=new FakeWorker(),b=new FakeWorker(),result=vi.fn();let count=0;const client=new ExecutionClient(result,()=> (++count===1?a:b) as unknown as Worker);client.start(request());client.cancel();expect(result.mock.calls[0]![0].status).toBe('cancelled');client.start(request('run-2'));a.send(runBytecode(request(),{nowMs:()=>0}));expect(result).toHaveBeenCalledOnce();b.send(runBytecode(request('run-2'),{nowMs:()=>0}));expect(result.mock.calls[1]![0].status).toBe('completed');});
 it('enforces exactly 1250 ms independent watchdog',()=>{vi.useFakeTimers();const w=new FakeWorker(),result=vi.fn(),client=new ExecutionClient(result,()=>w as unknown as Worker);client.start(request());vi.advanceTimersByTime(1249);expect(result).not.toHaveBeenCalled();vi.advanceTimersByTime(1);expect(result.mock.calls[0]![0]).toMatchObject({status:'incomplete-limit',diagnostics:[{code:'LIMIT_VM_TIME'}]});expect(w.terminate).toHaveBeenCalledOnce();});
 it.each(['schema','error','messageerror','postMessage','factory'])('fails safely on %s',kind=>{const w=new FakeWorker(),result=vi.fn();if(kind==='postMessage')w.postMessage.mockImplementation(()=>{throw new Error();});const client=new ExecutionClient(result,()=>{if(kind==='factory')throw new Error();return w as unknown as Worker;});client.start(request());if(kind==='schema')w.send({broken:true});if(kind==='error')w.onerror?.();if(kind==='messageerror')w.onmessageerror?.();expect(result.mock.calls[0]![0].diagnostics[0].code).toBe('WORKER_FAILED');});
});
