import { describe,it,expect } from 'vitest';
import { workspaceReducer,initialWorkspace } from '../../src/workspace/reducer.js';
import { canRun,canUseCurrentMarks } from '../../src/workspace/selectors.js';
import { analyzeSource } from '../../../../packages/core/src/analyze.js';
import { snapshot } from '../../../../packages/core/test/frontend-helper.js';
function partial(){let now=0;let state=workspaceReducer(initialWorkspace,{type:'EDIT_SOURCE',source:'shell(input("x"));'});state=workspaceReducer(state,{type:'START_ANALYSIS',requestId:'active',revision:state.revision});const result=analyzeSource({type:'analyze',protocolVersion:1,requestId:'active',snapshot:{...snapshot(state.source),revision:state.revision,snapshotId:`snapshot-${state.revision}-${snapshot(state.source).sha256}`},options:{recordReplay:true}},{nowMs:()=>now,onProgress:p=>{if(p.stage==='codegen')now=10000;}});return workspaceReducer(state,{type:'ANALYSIS_TERMINAL',result});}
describe('partial artifacts and replay state',()=>{
 it('labels an incomplete result while enabling valid partial graph inspection',()=>{let s=partial();expect(s.analysisStatus).toBe('incomplete-limit');expect(canRun(s,true)).toBe(false);expect(canUseCurrentMarks(s)).toBe(true);s=workspaceReducer(s,{type:'SELECT_NODE',id:'ir-0'});expect(s.selectedNodeId).toBe('ir-0');expect(workspaceReducer(s,{type:'SELECT_NODE',id:'ir-999'})).toBe(s);expect(workspaceReducer(s,{type:'SELECT_FINDING',id:'fake'})).toBe(s);});
 it('separates final view from recorded updates and bounds replay indexes',()=>{let s=partial();expect(s.replayMode).toBe('final');s=workspaceReducer(s,{type:'SET_REPLAY_INDEX',index:-1});expect(s.replayMode).toBe('updates');expect(workspaceReducer(s,{type:'SET_REPLAY_INDEX',index:99999})).toBe(s);s=workspaceReducer(s,{type:'SET_REPLAY_PLAYING',playing:true});expect(s.playing).toBe(true);s=workspaceReducer(s,{type:'SET_REPLAY_FINAL'});expect(s.playing).toBe(false);expect(s.replayMode).toBe('final');});
 it('retains immutable previous snapshot but rejects late layout/marks on edit',()=>{let s=partial();const result=s.currentAnalysis!;s=workspaceReducer(s,{type:'EDIT_SOURCE',source:'print(1);'});expect(s.currentAnalysis).toBe(result);expect(s.analysisStatus).toBe('stale');expect(canUseCurrentMarks(s)).toBe(false);expect(workspaceReducer(s,{type:'LAYOUT_RESULT',snapshotId:result.snapshot!.snapshotId,positions:{}})).toBe(s);expect(workspaceReducer(s,{type:'SET_REPLAY_PLAYING',playing:true})).toBe(s);});
 it('rejection of invalid-source result removes findings and graph presentation',()=>{let s=partial();s=workspaceReducer(s,{type:'EDIT_SOURCE',source:'print(unknown);'});s=workspaceReducer(s,{type:'START_ANALYSIS',requestId:'invalid',revision:s.revision});const snap=snapshot(s.source);s=workspaceReducer(s,{type:'ANALYSIS_TERMINAL',result:analyzeSource({type:'analyze',protocolVersion:1,requestId:'invalid',snapshot:{...snap,revision:s.revision,snapshotId:`snapshot-${s.revision}-${snap.sha256}`},options:{recordReplay:true}},{nowMs:()=>0})});expect(s.analysisStatus).toBe('invalid-source');expect(s.currentAnalysis?.artifacts.lowered).toBeUndefined();expect(s.currentAnalysis?.artifacts.findings).toBeUndefined();expect(s.graphLayoutStatus).toBe('idle');});
});
