import { afterEach,describe,it,expect,vi } from 'vitest';
import { AnalysisClient } from '../../src/adapters/workerClient.js';
import { LayoutClient } from '../../src/adapters/layoutClient.js';
import { snapshot } from '../../../../packages/core/test/frontend-helper.js';
import { analyzeSource } from '../../../../packages/core/src/analyze.js';
import type { AnalyzeRequest } from '@flowguard/core';
class FakeWorker {onmessage:((event:{data:unknown})=>void)|null=null;onerror:(()=>void)|null=null;onmessageerror:(()=>void)|null=null;terminate=vi.fn();postMessage=vi.fn();send(data:unknown){this.onmessage?.({data});}}
const request=(id='request-1'):AnalyzeRequest=>({type:'analyze',protocolVersion:1,requestId:id,snapshot:snapshot('shell(input("x"));'),options:{recordReplay:true}});
afterEach(()=>vi.useRealTimers());
describe('one-shot analysis transport',()=>{
 it('accepts progress and one matching terminal result then ignores duplicates',()=>{const w=new FakeWorker(),progress=vi.fn(),result=vi.fn(),client=new AnalysisClient(progress,result,()=>w as unknown as Worker),r=request();client.start(r);w.send({type:'progress',protocolVersion:1,requestId:r.requestId,revision:0,stage:'taint',completedWork:256});expect(progress).toHaveBeenCalledOnce();const terminal=analyzeSource(r,{nowMs:()=>0});w.send(terminal);w.send(terminal);expect(result).toHaveBeenCalledExactlyOnceWith(terminal);expect(w.terminate).toHaveBeenCalledOnce();});
 it('ignores retired-worker results after cancel/retry',()=>{const a=new FakeWorker(),b=new FakeWorker(),result=vi.fn();let count=0;const client=new AnalysisClient(()=>{},result,()=> (++count===1?a:b) as unknown as Worker);const first=request();client.start(first);client.cancel(false);client.start(request('request-2'));a.send(analyzeSource(first,{nowMs:()=>0}));expect(result).not.toHaveBeenCalled();b.send(analyzeSource(request('request-2'),{nowMs:()=>0}));expect(result).toHaveBeenCalledOnce();expect(a.terminate).toHaveBeenCalledOnce();});
 it.each(['malformed','wrong-id','wrong-snapshot','error','messageerror','postMessage','factory'])('maps %s to WORKER_FAILED',kind=>{const w=new FakeWorker(),result=vi.fn(),r=request();if(kind==='postMessage')w.postMessage.mockImplementation(()=>{throw new Error();});const client=new AnalysisClient(()=>{},result,()=>{if(kind==='factory')throw new Error();return w as unknown as Worker;});client.start(r);const terminal=analyzeSource(r,{nowMs:()=>0});if(kind==='malformed')w.send({broken:true});if(kind==='wrong-id')w.send({...terminal,requestId:'wrong'});if(kind==='wrong-snapshot')w.send({...terminal,snapshot:snapshot('print(1);')});if(kind==='error')w.onerror?.();if(kind==='messageerror')w.onmessageerror?.();expect(result.mock.calls[0]?.[0].diagnostics[0].code).toBe('WORKER_FAILED');});
 it('enforces watchdog and termination-based cancellation',()=>{vi.useFakeTimers();const w=new FakeWorker(),result=vi.fn(),client=new AnalysisClient(()=>{},result,()=>w as unknown as Worker);client.start(request());vi.advanceTimersByTime(10250);expect(result.mock.calls[0]![0].status).toBe('incomplete-limit');expect(w.terminate).toHaveBeenCalledOnce();client.start(request());client.cancel();expect(result.mock.calls[1]![0].status).toBe('cancelled');vi.advanceTimersByTime(20000);expect(result).toHaveBeenCalledTimes(2);});
});
describe('layout identity and fallback',()=>{
 const program=analyzeSource(request(),{nowMs:()=>0}).artifacts.lowered!;
 it('accepts exact node positions and ignores duplicate results',()=>{const w=new FakeWorker(),result=vi.fn(),error=vi.fn(),client=new LayoutClient(result,error,()=>w as unknown as Worker);client.start('snapshot',program);const raw=w.postMessage.mock.calls[0]![0] as {requestId:string};const message={type:'layout-result',protocolVersion:1,requestId:raw.requestId,snapshotId:'snapshot',positions:Object.fromEntries(program.instructions.map(n=>[n.id,{x:0,y:1}]))};w.send(message);w.send(message);expect(result).toHaveBeenCalledOnce();expect(error).not.toHaveBeenCalled();});
 it.each(['missing','nan','wrong-id','timeout','error'])('falls back on %s',kind=>{vi.useFakeTimers();const w=new FakeWorker(),result=vi.fn(),error=vi.fn(),client=new LayoutClient(result,error,()=>w as unknown as Worker);client.start('snapshot',program);const raw=w.postMessage.mock.calls[0]![0] as {requestId:string};if(kind==='timeout')vi.advanceTimersByTime(2000);else if(kind==='error')w.onerror?.();else w.send({type:'layout-result',protocolVersion:1,requestId:kind==='wrong-id'?'wrong':raw.requestId,snapshotId:'snapshot',positions:kind==='missing'?{}:Object.fromEntries(program.instructions.map(n=>[n.id,{x:kind==='nan'?NaN:0,y:1}]))});expect(error).toHaveBeenCalledOnce();expect(result).not.toHaveBeenCalled();expect(w.terminate).toHaveBeenCalledOnce();});
 it('skips interactive layout above 200 nodes',()=>{const error=vi.fn(),factory=vi.fn(),client=new LayoutClient(()=>{},error,factory);client.start('snapshot',{...program,instructions:Array(201).fill(program.instructions[0])});expect(factory).not.toHaveBeenCalled();expect(error.mock.calls[0]![1]).toContain('Large graph');});
});
