import { describe,it,expect } from 'vitest';
import { snapshot } from './frontend-helper.js';
import { analyzeSource } from '../src/analyze.js';
import { AnalysisResultSchema } from '../src/contracts.js';
const request=(source:string,replay=true)=>({type:'analyze',protocolVersion:1,requestId:'test-1',snapshot:snapshot(source),options:{recordReplay:replay}});
describe('completed compiler coordinator',()=>{
 it('publishes findings and bytecode only after all stages complete',()=>{const stages:string[]=[];const r=analyzeSource(request('sql_query(input("x"));'),{nowMs:()=>0,onProgress:p=>stages.push(p.stage)});expect(r.completedStages).toEqual(['validate','lex','parse','semantic','lower','taint','findings','codegen','verify']);expect(r.status).toBe('completed');expect(r.diagnostics).toEqual([]);expect(r.artifacts.findings).toHaveLength(1);expect(r.artifacts.bytecode?.maxVerifiedStack).toBe(1);expect(r.artifacts.explanations?.length).toBeGreaterThan(0);expect(stages).toEqual(r.completedStages);expect(AnalysisResultSchema.safeParse(r).success).toBe(true);});
 it.each(['codegen','verify'])('withholds final artifacts when %s hits its shared deadline',stage=>{let now=0;const r=analyzeSource(request('sql_query(input("x"));'),{nowMs:()=>now,onProgress:p=>{if(p.stage===stage)now=10000;}});expect(r.status).toBe('incomplete-limit');expect(r.artifacts.findings).toBeUndefined();expect(r.artifacts.bytecode).toBeUndefined();expect(r.artifacts.disassembly).toBeUndefined();expect(r.artifacts.taint).toBeDefined();expect(AnalysisResultSchema.safeParse(r).success).toBe(true);});
 it.each([['@','lex',[]],['let x:int;','parse',['tokens']],['print(x);','semantic',['tokens','ast','semantic']]] as const)('retains only completed artifacts for %s',(source,stage,keys)=>{const r=analyzeSource(request(source),{nowMs:()=>0});expect(r.status).toBe('invalid-source');expect(r.diagnostics[0]!.stage).toBe(stage);expect(Object.keys(r.artifacts)).toEqual(keys);expect(AnalysisResultSchema.safeParse(r).success).toBe(true);});
 it('supports replay opt-out, dynamic-template notice and empty source',()=>{const r=analyzeSource(request('let t:string="?";sql_bind(t,1);',false),{nowMs:()=>0});expect(r.artifacts.replay).toBeUndefined();expect(r.diagnostics[0]!.code).toBe('TEMPLATE_UNVERIFIED');expect(analyzeSource(request(''),{nowMs:()=>0}).artifacts.lowered?.instructions).toHaveLength(1);});
 it('maps invalid envelopes, source limits and cancellation',()=>{const invalid=analyzeSource({protocolVersion:2},{nowMs:()=>0});expect(invalid.status).toBe('invalid-request');expect(invalid.diagnostics[0]!.code).toBe('SCHEMA_UNSUPPORTED');expect(AnalysisResultSchema.safeParse(invalid).success).toBe(true);const limited=analyzeSource(request(' '.repeat(262145)),{nowMs:()=>0});expect(limited.status).toBe('incomplete-limit');expect(limited.diagnostics[0]!.code).toBe('LIMIT_SOURCE');const cancelled=analyzeSource(request('print(1);'),{nowMs:()=>0,checkpointAbort:()=>true});expect(cancelled.status).toBe('cancelled');expect(cancelled.artifacts).toEqual({});});
});
