import { describe,it,expect } from 'vitest';
import { generateBytecode,disassembleBytecode } from '../src/codegen.js';
import { verifyBytecode } from '../src/verify.js';
import { OPCODES } from '../src/contracts.js';
import { DEFAULT_LIMITS } from '../src/limits.js';
import { artifact } from './bytecode-helper.js';
import { lowered,snapshot,guard } from './frontend-helper.js';
import type { BytecodeInstruction } from '../src/model.js';
const i=(opcode:BytecodeInstruction['opcode'],...operands:number[]):BytecodeInstruction=>({opcode,operands});
describe('typed bytecode generation and verification',()=>{
 it('generates every opcode, ordered input identities, first-use typed constants and complete mappings',()=>{
  const source='let x:int=1;let y:int=2;let s:string=input("x");let t:string=input("x");print(-x);print(!false);print(x+y);print(x-y);print(x*y);print(x/y);print(x%y);print(s+t);print(x<y);print(x<=y);print(x>y);print(x>=y);print(x==y);print(s!=t);if(true){print(1);}sql_query(s);sql_bind("?",s);shell(t);';
  const p=lowered(source).lowered,b=generateBytecode(p,snapshot(source),guard());expect(new Set(b.instructions.map(n=>n.opcode))).toEqual(new Set(OPCODES));expect(b.sourceIds).toEqual(['src-0','src-1']);expect(b.constants.filter(c=>c.value==='x')).toHaveLength(1);expect(b.constants.findIndex(c=>c.type==='int'&&c.value===1)).toBe(0);expect(verifyBytecode(b,guard())).toBe(2);expect(disassembleBytecode(b)).toHaveLength(b.instructions.length);
  for(const mapping of b.sourceMap){const node=p.instructions.find(n=>n.id===mapping.irNodeId)!;expect(mapping.astId).toBe(node.astId);expect(mapping.span).toEqual(node.span);}
  for(const n of b.instructions.filter(n=>n.opcode==='JUMP'||n.opcode==='JUMP_IF_FALSE')){const pc=n.operands[0]!;expect(pc===0||b.sourceMap[pc]!.irNodeId!==b.sourceMap[pc-1]!.irNodeId).toBe(true);}
 });
 it('deduplicates bool/int/string separately and preserves deterministic output',()=>{const source='print(1);print(true);print("1");print(1);',p=lowered(source).lowered;const b=generateBytecode(p,snapshot(source),guard());expect(b.constants).toEqual([{type:'int',value:1},{type:'bool',value:true},{type:'string',value:'1'}]);expect(generateBytecode(p,snapshot(source),guard())).toEqual(b);});
 it('carries only the final lexical scope in symbol order',()=>{const source='let first:int=1;{let local:string="secret";print(local);}let last:bool=false;',p=lowered(source),b=generateBytecode(p.lowered,snapshot(source),guard());expect(b.topLevelSymbolIds).toEqual(['sym-0','sym-2']);expect(b.topLevelSymbolIds).toEqual(p.semantic.symbols.filter(s=>s.topLevel).map(s=>s.id));expect(generateBytecode(lowered('').lowered,snapshot(''),guard()).topLevelSymbolIds).toEqual([]);});
 it.each(['missing','duplicate','order','unknown','temporary'])('rejects %s top-level scope metadata',kind=>{const b=artifact([i('HALT')]);b.slots=[{id:'slot-0',type:'int',displayName:'first',temporary:false,symbolId:'sym-0'},{id:'slot-1',type:'int',displayName:'last',temporary:false,symbolId:'sym-1'}];b.topLevelSymbolIds=['sym-0','sym-1'];if(kind==='missing')delete (b as Partial<typeof b>).topLevelSymbolIds;if(kind==='duplicate')b.topLevelSymbolIds=['sym-0','sym-0'];if(kind==='order')b.topLevelSymbolIds=['sym-1','sym-0'];if(kind==='unknown')b.topLevelSymbolIds=['sym-9'];if(kind==='temporary')b.slots[0]!.temporary=true;expect(()=>verifyBytecode(b,guard())).toThrow('Invalid bytecode schema');});
 it('accepts loop-carried initialized values after convergence',()=>{const source='let x:int=0;while(x<3){x=x+1;}print(x);';expect(verifyBytecode(generateBytecode(lowered(source).lowered,snapshot(source),guard()),guard())).toBe(2);});
 it('uses an external empty entry even on a backedge',()=>{expect(()=>verifyBytecode(artifact([i('LOAD',0),i('STORE',0),i('JUMP',0)]),guard())).toThrow('not definitely initialized');});
 it('rejects a LOAD initialized on only one branch',()=>{const b=artifact([i('PUSH_CONST',0),i('JUMP_IF_FALSE',5),i('PUSH_CONST',1),i('STORE',0),i('JUMP',5),i('LOAD',0),i('PRINT'),i('HALT')],[{type:'bool',value:true},{type:'int',value:1}]);expect(()=>verifyBytecode(b,guard())).toThrow('not definitely initialized');});
 it.each([
  [i('PUSH_CONST',0),i('HALT')], [i('LOAD',0),i('PRINT'),i('HALT')], [i('JUMP',999)], [i('PUSH_CONST',99),i('PRINT'),i('HALT')], [i('LOAD',99),i('PRINT'),i('HALT')], [i('INPUT',0),i('PRINT'),i('HALT')], [i('PRINT')], [i('PUSH_CONST',0),i('NOT_BOOL'),i('PRINT'),i('HALT')], [i('PUSH_CONST',0),i('PUSH_CONST',1),i('EQ'),i('PRINT'),i('HALT')]
 ].map(code=>({code})))('rejects malformed references, stack types, underflow, and falloff %#',({code})=>{expect(()=>verifyBytecode(artifact(code,[{type:'int',value:1},{type:'string',value:'x'}]),guard())).toThrow();});
 it('rejects differing types/depths at joins',()=>{for(const tail of [[i('PUSH_CONST',1),i('JUMP',5)],[i('JUMP',5),i('JUMP',5)]]){const b=artifact([i('PUSH_CONST',0),i('JUMP_IF_FALSE',4),...tail,i('PUSH_CONST',0),i('PRINT'),i('HALT')],[{type:'bool',value:true},{type:'int',value:1}]);expect(()=>verifyBytecode(b,guard())).toThrow();}});
 it('enforces stack cap at max + 1 and does not trust declared maximum',()=>{const valid=artifact([...Array.from({length:1024},()=>i('PUSH_CONST',0)),...Array.from({length:1024},()=>i('PRINT')),i('HALT')],[{type:'int',value:1}]);expect(verifyBytecode(valid,guard())).toBe(1024);valid.instructions.splice(0,0,i('PUSH_CONST',0));valid.sourceMap=valid.instructions.map((_,pc)=>({...valid.sourceMap[0]!,pc}));expect(()=>verifyBytecode(valid,guard())).toThrow('stack exceeds');});
 it.each(['version','arity','map','constant','slot','checksum','source'])('rejects invalid %s metadata',kind=>{const b=artifact([i('HALT')]);if(kind==='version')b.version=2 as 1;if(kind==='arity')b.instructions[0]!.operands=[0];if(kind==='map')b.sourceMap=[];if(kind==='constant')b.constants=[{type:'int',value:2147483648}];if(kind==='slot')b.slots[0]!.id='slot-9';if(kind==='checksum')b.snapshotId='other';if(kind==='source')b.sourceIds=['src-1','src-0'];expect(()=>verifyBytecode(b,guard())).toThrow();});
 it('enforces each verifier pass visit budget and the shared deadline',()=>{const b=artifact([i('HALT')]),g=guard();Object.defineProperty(g,'limits',{value:{...DEFAULT_LIMITS,maxVerifierVisits:0}});expect(()=>verifyBytecode(b,g)).toThrow('maxVerifierVisits');const h=guard();Object.defineProperty(h,'limits',{value:{...DEFAULT_LIMITS,analysisDeadlineMs:0}});expect(()=>verifyBytecode(b,h)).toThrow('deadline');});
 it('checks LOAD only after a later predecessor has converged and caps that second pass',()=>{const b=artifact([i('JUMP',4),i('LOAD',0),i('PRINT'),i('HALT'),i('PUSH_CONST',0),i('STORE',0),i('JUMP',1)],[{type:'int',value:1}]);expect(verifyBytecode(b,guard())).toBe(1);const g=guard();Object.defineProperty(g,'limits',{value:{...DEFAULT_LIMITS,maxVerifierVisits:7}});expect(()=>verifyBytecode(b,g)).toThrow('maxVerifierVisits');});
 it('checks code generation instruction cap on the attempt to exceed it',()=>{const g=guard();Object.defineProperty(g,'limits',{value:{...DEFAULT_LIMITS,maxBytecodeInstructions:1}});expect(generateBytecode(lowered('').lowered,snapshot(''),g).instructions).toHaveLength(1);expect(()=>generateBytecode(lowered('print(1);').lowered,snapshot('print(1);'),g)).toThrow('maxBytecodeInstructions');});
});
