import { describe,it,expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { adjacency, validateLoweredProgram } from '../src/graph.js';
import { LoweredProgramSchema,ProgramSchema,SemanticModelSchema } from '../src/contracts.js';
import { LimitFailure } from '../src/diagnostics.js';
import type { LoweredInstruction,LoweredProgram } from '../src/model.js';
import { lowered,guard } from './frontend-helper.js';
// Independent definite-assignment check over structural paths, including loops.
function verifyInitialized(p:LoweredProgram){
 const {predecessors}=adjacency(p),all=new Set(p.slots.map(s=>s.id)),out=new Map(p.instructions.map(i=>[i.id,new Set(all)]));
 let changed=true;while(changed){changed=false;for(const i of p.instructions){const previous=predecessors.get(i.id)!;const input=i.id===p.entryNodeId?new Set<string>():previous.length?new Set([...out.get(previous[0]!.from)!].filter(s=>previous.every(e=>out.get(e.from)!.has(s)))):new Set<string>();const next=new Set(input);if('dst' in i)next.add(i.dst);if([...next].join()!==[...out.get(i.id)!].join()){out.set(i.id,next);changed=true;}}}
 const reads=(i:LoweredInstruction)=>i.op==='copy'||i.op==='unary'?[i.src]:i.op==='binary'?[i.left,i.right]:i.op==='input'?[i.promptSlot]:i.op==='effect'?i.argSlots:i.op==='branch'?[i.conditionSlot]:[];
 for(const i of p.instructions){const prev=predecessors.get(i.id)!;for(const slot of reads(i))expect(prev.length>0&&prev.every(e=>out.get(e.from)!.has(slot)),`${i.id} reads ${slot} before definition`).toBe(true);}
}
describe('lowering',()=>{
 it('empty and comment-only programs produce the real halt-only graph',()=>{for(const source of ['', '/* empty */']){const p=lowered(source).lowered;expect(p.slots).toEqual([]);expect(p.instructions.map(i=>i.op)).toEqual(['halt']);expect(p.edges).toEqual([]);expect(p.entryNodeId).toBe(p.exitNodeId);}});
 it('preserves left-to-right calls, ordinary temp order, source links, and visibility',()=>{const {lowered:p,ast,semantic}=lowered('let x: string = input("a") + input("b"); {let y: string = x; print(y);} print(x);');expect(p.instructions.filter(i=>i.op==='input').map(i=>i.sourceId)).toEqual(['src-0','src-1']);expect(p.slots.filter(s=>!s.temporary).map(s=>s.id)).toEqual(['slot-0','slot-1']);expect(p.instructions.filter(i=>'dst' in i&&i.op!=='copy').map(i=>i.dst)).toEqual(['slot-2','slot-3','slot-4','slot-5','slot-6']);const effects=p.instructions.filter(i=>i.op==='effect');expect(effects[0]!.visibleSymbolIds).toEqual(['sym-0','sym-1']);expect(effects[1]!.visibleSymbolIds).toEqual(['sym-0']);expect(ProgramSchema.safeParse(ast).success).toBe(true);expect(SemanticModelSchema.safeParse(semantic).success).toBe(true);expect(LoweredProgramSchema.safeParse(p).success).toBe(true);verifyInitialized(p);});
 it('keeps both short-circuit alternatives and joins result definitions',()=>{const p=lowered('let b: bool = false && (input("a") == "x") || (true || (input("b") == "y")); print(b);').lowered;expect(p.instructions.filter(i=>i.op==='branch')).toHaveLength(3);expect(p.instructions.filter(i=>i.op==='input')).toHaveLength(2);expect(p.instructions.some(i=>i.op==='binary'&&(i.operator as string)==='&&')).toBe(false);const first=p.instructions.find(i=>i.op==='branch')!;if(first.op!=='branch')throw Error();const trueIndex=Number(first.trueTarget.slice(3)),falseIndex=Number(first.falseTarget.slice(3));expect(p.instructions[falseIndex]).toMatchObject({op:'const',scalar:{type:'bool',value:false}});expect(p.instructions.slice(trueIndex).find(i=>i.op==='input')).toMatchObject({sourceId:'src-0'});verifyInitialized(p);});
 it('builds if joins, missing-else false path, and while zero/body/back/exit paths',()=>{const p=lowered('let n: int = 0; if (true) { n = 1; } while (n < 3) { let s: string = input("loop"); n = n + 1; print(s); } print(n);').lowered;expect(p.edges.filter(e=>e.kind==='loop-back')).toHaveLength(1);const back=p.edges.find(e=>e.kind==='loop-back')!;expect(Number(back.to.slice(3))).toBeLessThan(Number(back.from.slice(3)));const branches=p.instructions.filter(i=>i.op==='branch');expect(p.instructions[Number(branches[0]!.falseTarget.slice(3))]).toMatchObject({op:'jump'});expect(p.edges.filter(e=>e.from===branches[1]!.id).map(e=>e.kind)).toEqual(['true','false']);expect(p.instructions.filter(i=>i.op==='input')).toHaveLength(1);verifyInitialized(p);});
 it('compiles every synthetic example with valid source links and initialized reads',()=>{for(const name of ['unsafe-query','bound-query','branch-merge','trusted-overwrite','loop-flow','multiple-sources','short-circuit','arithmetic-loop','runtime-error']){const source=readFileSync(resolve('examples',`${name}.fg`),'utf8'),r=lowered(source);expect(r.semantic.diagnostics.filter(d=>d.blocking),name).toEqual([]);verifyInitialized(r.lowered);for(const i of r.lowered.instructions)expect(source.slice(i.span.start,i.span.end).length).toBeGreaterThan(0);}});
 it('rejects corrupted targets, slots, edges, owners and source maps',()=>{const r=lowered('let x: int = 1; while (x < 2) {x = x + 1;}');for(const mutate of [(p:LoweredProgram)=>{const branch=p.instructions.find(i=>i.op==='branch')!;if(branch.op==='branch')branch.trueTarget='ir-999';},(p:LoweredProgram)=>{p.slots[0]!.type='bool';},(p:LoweredProgram)=>{p.edges.pop();},(p:LoweredProgram)=>{p.instructions[0]!.astId='ast-999';},(p:LoweredProgram)=>{delete p.sourceMap['ir-0'];}]){const p=structuredClone(r.lowered);mutate(p);expect(()=>validateLoweredProgram(p,r.ast,r.semantic,guard())).toThrow();}});
 it('enforces CFG/total-slot budgets, and traverses deep left-associated trees without recursion overflow',()=>{const exact='let x: int = 0;'+'print(0);'.repeat(998)+'print(x);';expect(lowered(exact).lowered.instructions).toHaveLength(2000);expect(()=>lowered(exact+'print(x);')).toThrow(LimitFailure);expect(()=>lowered('print(0);'.repeat(1000))).toThrow(LimitFailure);expect(()=>lowered('print('+Array(2100).fill('1').join('+')+');')).toThrow(LimitFailure);});
});
