import { describe,it,expect } from 'vitest';
import { staticAnalysis } from './static-helper.js';
import { buildProvenance } from '../src/provenance.js';
import { BudgetGuard,DEFAULT_LIMITS } from '../src/limits.js';
import { guard } from './frontend-helper.js';
describe('bounded final-state explanations',()=>{
 it('links sources, copies, and operators with complete references',()=>{const r=staticAnalysis('let a:string=input("a");let b:string=a+input("b");shell(b);');const facts=buildProvenance(r.lowered,r.taint,r.findings,guard());expect(r.findings[0]!.explanationComplete).toBe(true);expect(facts.filter(f=>f.kind==='source').map(f=>f.sourceId).sort()).toEqual(['src-0','src-1']);expect(facts.some(f=>f.kind==='operator')).toBe(true);const ids=new Set(facts.map(f=>f.id));expect(facts.every(f=>f.predecessorFactIds.every(id=>ids.has(id)))).toBe(true);});
 it('represents branch merges and cyclic loop contributions finitely',()=>{const r=staticAnalysis('let a:string=input("a");while(true){a=a+"x";}shell(a);');const facts=buildProvenance(r.lowered,r.taint,r.findings,guard());expect(facts.some(f=>f.kind==='cycle')).toBe(true);expect(facts.some(f=>f.kind==='merge')).toBe(true);expect(facts.length).toBeLessThan(200);expect(r.findings[0]!.explanationComplete).toBe(true);});
 it.each([['maxProvenanceFacts',1],['maxExplanationFacts',1]] as const)('truncates %s without discarding sources',(key,value)=>{const r=staticAnalysis('let a:string=input("a");shell(a+input("b"));');const g=new BudgetGuard({nowMs:()=>0});Object.defineProperty(g,'limits',{value:{...DEFAULT_LIMITS,[key]:value}});const facts=buildProvenance(r.lowered,r.taint,r.findings,g);expect(r.findings[0]!.sourceIds).toEqual(['src-0','src-1']);expect(r.findings[0]!.explanationComplete).toBe(false);expect(key==='maxProvenanceFacts'?facts.length:r.findings[0]!.explanationFactIds.length).toBeLessThanOrEqual(value);});
 it('shares deduplicated facts across multiple sinks deterministically',()=>{const r=staticAnalysis('let a:string=input("a");shell(a);sql_query(a);');const facts=buildProvenance(r.lowered,r.taint,r.findings,guard());expect(new Set(facts.map(f=>`${f.nodeId}:${f.slotId}:${f.sourceId}:${f.kind}`)).size).toBe(facts.length);expect(r.findings.every(f=>f.explanationComplete)).toBe(true);expect(r.findings.every(f=>f.explanationFactIds.some(id=>facts.find(x=>x.id===id)?.kind==='source'))).toBe(true);});
});
