import { describe,it,expect } from 'vitest';
import { lowered,guard } from './frontend-helper.js';
import { ReplayRecorder,reconstructReplay,applyReplayEvent } from '../src/replay.js';
import { solveTaint } from '../src/taint.js';
import { DEFAULT_LIMITS } from '../src/limits.js';
describe('analysis replay',()=>{
 it('reconstructs convergence and undo/redo across loop updates',()=>{const p=lowered('let a:string="";while(true){a=a+input("a");}shell(a);').lowered,recorder=new ReplayRecorder(p),r=solveTaint(p,guard(),recorder);const trace=recorder.trace;expect(trace.truncated).toBe(false);const final=reconstructReplay(trace,trace.events.length-1);expect(final).toEqual(Object.fromEntries(Object.entries(r.states).map(([id,s])=>[id,s.out])));for(let i=0;i<trace.events.length;i++){const before=reconstructReplay(trace,i-1),after=applyReplayEvent(before,trace.events[i]!);expect(applyReplayEvent(after,trace.events[i]!,true)).toEqual(before);}expect(Object.values(reconstructReplay(trace,-1)).every(s=>!s.reachable)).toBe(true);});
 it('records checkpoints at 100 changes without mutating prior checkpoints',()=>{const source=Array.from({length:60},(_,i)=>`let a${i}:int=${i};`).join('');const p=lowered(source).lowered,recorder=new ReplayRecorder(p);const r=solveTaint(p,guard(),recorder);expect(recorder.trace.checkpoints.map(c=>c.eventIndex)).toEqual([-1,99]);expect(Object.values(recorder.trace.checkpoints[0]!.outputs).every(s=>!s.reachable)).toBe(true);expect(reconstructReplay(recorder.trace,119)[p.exitNodeId]?.reachable).toBe(false);expect(reconstructReplay(recorder.trace,recorder.trace.events.length-1)[p.exitNodeId]).toEqual(r.states[p.exitNodeId]!.out);});
 it('stops at count cap and counts omitted updates without affecting solver',()=>{const p=lowered('print(1);').lowered,recorder=new ReplayRecorder(p),state={reachable:true,entries:p.slots.map(s=>({slotId:s.id,sourceIds:[]}))};for(let i=0;i<DEFAULT_LIMITS.maxReplayEvents+2;i++)recorder.record(p.entryNodeId,{reachable:false,entries:[]},state);expect(recorder.trace.events.length).toBe(DEFAULT_LIMITS.maxReplayEvents);expect(recorder.trace.truncated).toBe(true);expect(recorder.trace.droppedEventCount).toBe(2);expect(()=>solveTaint(p,guard(),recorder)).not.toThrow();});
 it('rejects invalid indexes',()=>{const trace=new ReplayRecorder(lowered('').lowered).trace;expect(()=>reconstructReplay(trace,0)).toThrow();expect(()=>reconstructReplay(trace,-2)).toThrow();});
 it('accounts for escaped JSON and stops at byte budget without a solver failure',()=>{const p=lowered('print(1);').lowered,recorder=new ReplayRecorder(p),sourceIds=Array.from({length:256},(_,i)=>`src-${i}`),state={reachable:true,entries:Array.from({length:1000},(_,i)=>({slotId:`slot-${i}`,sourceIds}))};for(let i=0;i<10;i++)recorder.record(p.entryNodeId,{reachable:false,entries:[]},state);expect(recorder.trace.truncated).toBe(true);expect(recorder.trace.events.length).toBeGreaterThan(0);expect(recorder.trace.events.length).toBeLessThan(10);expect(new TextEncoder().encode(JSON.stringify(recorder.trace)).length).toBeLessThanOrEqual(DEFAULT_LIMITS.maxReplayBytes);});
});
