import { describe,it,expect } from 'vitest';
import { front,lowered } from './frontend-helper.js';
import { SourceFailure,LimitFailure } from '../src/diagnostics.js';
const codes=(source:string)=>front(source).semantic.diagnostics.map(d=>d.code);
describe('semantics',()=>{
 it('resolves initialized declarations, sibling scopes, and stable input sources',()=>{const s=front('let x: int = 1; { let y: string = input(input("a")); print(y); } { let y: bool = true; print(y); }').semantic;expect(s.diagnostics).toEqual([]);expect(s.symbols.map(s=>s.id)).toEqual(['sym-0','sym-1','sym-2']);expect(s.symbols.map(s=>s.topLevel)).toEqual([true,false,false]);expect(s.scopes[1]!.parentId).toBe('scope-0');expect(s.inputSources.map(s=>s.id)).toEqual(['src-0','src-1']);expect(s.inputSources[0]!.span.start).toBeLessThan(s.inputSources[1]!.span.start);});
 it.each([
 ['let x: int = x;','SEM_UNDECLARED'],['let x: int = 0; let x: int = 1;','SEM_DUPLICATE'],['let x: int = 0; {let x: int = 1;}','SEM_SHADOWING'],['{let x: int = 0;} print(x);','SEM_UNDECLARED'],['x = 1;','SEM_UNDECLARED'],['let x: int = true;','SEM_TYPE'],['let x: int = 1; x = "a";','SEM_TYPE'],['if (1) {}','SEM_TYPE'],['while ("x") {}','SEM_TYPE'],['print(1 + "a");','SEM_TYPE'],['print("a" < "b");','SEM_TYPE'],['print(1 == true);','SEM_TYPE'],['print(!1);','SEM_TYPE'],['print(-true);','SEM_TYPE'],['print(true && 1);','SEM_TYPE'],['print("a" - "b");','SEM_TYPE'],['print(input(1));','SEM_TYPE'],['shell(1);','SEM_TYPE'],['sql_query(true);','SEM_TYPE'],['print();','SEM_ARGUMENTS'],['print(1, 2);','SEM_ARGUMENTS'],['sql_bind("?");','SEM_ARGUMENTS'],['sql_bind("", 1);','SEM_TEMPLATE_PLACEHOLDERS'],['sql_bind("??", 1);','SEM_TEMPLATE_PLACEHOLDERS']
 ])('rejects %s with %s',(source,code)=>{expect(codes(source)).toContain(code);expect(()=>lowered(source)).toThrow(SourceFailure);});
 it('accepts every scalar operator signature and bound scalar type',()=>{expect(codes('let i: int = -2147483647 - 1; let s: string = "a" + "b"; let b: bool = !false || true && (i <= 1) && (s == "ab"); print(i * 2 / 1 % 3); print(i > 0); print(i >= 0); print(i != 0); sql_bind("?", b); sql_bind("?", i); sql_bind("?", s);')).toEqual([]);});
 it('emits a nonblocking notice for every nonliteral template without folding',()=>{const model=front('let t: string = "?"; sql_bind(t, 1); sql_bind("?" + "", true);').semantic;expect(model.diagnostics).toHaveLength(2);expect(model.diagnostics.every(d=>d.code==='TEMPLATE_UNVERIFIED'&&!d.blocking&&d.severity==='notice')).toBe(true);expect(()=>lowered('let t: string = "?"; sql_bind(t, 1);')).not.toThrow();});
 it('caps diagnostics at 100 plus terminal cap notice',()=>{const s=front('print(x);'.repeat(101)).semantic;expect(s.diagnostics).toHaveLength(101);expect(s.diagnostics.at(-1)!.code).toBe('TOO_MANY_DIAGNOSTICS');});
 it('enforces source and user-slot caps',()=>{expect(front('print(input("x"));'.repeat(256)).semantic.inputSources).toHaveLength(256);expect(()=>front('print(input("x"));'.repeat(257))).toThrow(LimitFailure);expect(front(Array.from({length:4000},(_,i)=>`let n${i}: int = 0;`).join('')).semantic.symbols).toHaveLength(4000);expect(()=>front(Array.from({length:4001},(_,i)=>`let n${i}: int = 0;`).join(''))).toThrow(LimitFailure);});
});
