import { describe,it,expect } from 'vitest';
import { analyzeSource } from '../src/analyze.js';
import { runBytecode } from '../src/vm.js';
import { ExecutionResultSchema } from '../src/contracts.js';
import { snapshot } from './frontend-helper.js';
import { artifact } from './bytecode-helper.js';
import type { BudgetHooks } from '../src/limits.js';
import type { BytecodeArtifact } from '../src/model.js';
function run(source:string,inputs:string[]=[],hooks:BudgetHooks={nowMs:()=>0}){const snap=snapshot(source),a=analyzeSource({type:'analyze',protocolVersion:1,requestId:'vm-analysis',snapshot:snap,options:{recordReplay:false}},{nowMs:()=>0});expect(a.status,a.diagnostics.map(d=>d.message).join(',')).toBe('completed');return execute(a.artifacts.bytecode!,inputs,hooks);}
function execute(bytecode:BytecodeArtifact,inputs:string[]=[],hooks:BudgetHooks={nowMs:()=>0}){const r=runBytecode({type:'execute',protocolVersion:1,requestId:'vm-1',revision:0,snapshotId:bytecode.snapshotId,bytecode,inputs},hooks);expect(ExecutionResultSchema.safeParse(r).success).toBe(true);return r;}
const printed=(r:ReturnType<typeof run>)=>r.events.filter(e=>e.kind==='print').map(e=>e.value.value);
describe('bounded typed VM',()=>{
 it('reports initialized top-level values in symbol order after assignment, excluding locals and temporaries',()=>{const r=run('let first:int=1;{let local:string="secret";print(local);}let last:bool=false;first=3;');expect(r.status).toBe('completed');expect(r.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'first',value:{type:'int',value:3}},{symbolId:'sym-2',name:'last',value:{type:'bool',value:false}}]);expect(run('{let local:int=1;}').finalTopLevelValues).toEqual([]);expect(run('').finalTopLevelValues).toEqual([]);});
 it('retains initialized values on runtime failure and omits declarations not reached',()=>{const r=run('let saved:int=7;{let local:string="private";}let pending:string=input("x");let later:bool=true;');expect(r.status).toBe('runtime-error');expect(r.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'saved',value:{type:'int',value:7}}]);});
 it('retains initialized top-level values on limits and cooperative cancellation',()=>{const limited=run('let saved:int=7;let ticks:int=0;while(true){ticks=ticks+1;}');expect(limited.status).toBe('incomplete-limit');expect(limited.finalTopLevelValues.map(v=>v.name)).toEqual(['saved','ticks']);expect(limited.finalTopLevelValues[0]!.value.value).toBe(7);expect(limited.finalTopLevelValues[1]!.value.value).toBeGreaterThan(0);let checks=0;const cancelled=run('let kept:int=4;{let local:int=8;}print(kept);while(true){}',[],{nowMs:()=>0,checkpointAbort:()=>++checks>=5});expect(cancelled.status).toBe('cancelled');expect(cancelled.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'kept',value:{type:'int',value:4}}]);});
 it('does not report values from unverified metadata',()=>{const b=artifact([{opcode:'HALT',operands:[]}]);b.topLevelSymbolIds=['sym-999'];const r=execute(b);expect(r.status).toBe('internal-error');expect(r.finalTopLevelValues).toEqual([]);});
 it('executes all scalar operators, precedence and negative truncating division/remainder',()=>{const r=run('print(1+2*3);print(9-5);print(-7/3);print(-7%3);print(7/-3);print(7%-3);print(!false);print("a"+"b");print(1<2);print(1<=1);print(2>1);print(2>=2);print(true==true);print("x"!="y");');expect(r.status).toBe('completed');expect(printed(r)).toEqual([7,4,-2,-1,-2,1,true,'ab',true,true,true,true,true,true]);});
 it('executes finite loops and source encounter order including repeated input sites',()=>{const r=run('let i:int=0;while(i<2){print(input("again"));i=i+1;}print(input("last"));',['a','b','c','unused']);expect(r.status).toBe('completed');expect(printed(r)).toEqual(['a','b','c']);expect(r.consumedInputCount).toBe(3);expect(r.events.filter(e=>e.kind==='input').map(e=>e.sourceId)).toEqual(['src-0','src-0','src-1']);});
 it.each([['false &&',0,false],['true ||',0,true],['true &&',1,true],['false ||',1,true]] as const)('honors %s short circuit', (operator,consumed,value)=>{const r=run(`print(${operator} input("skipped") == "yes");`,['yes']);expect(r.status).toBe('completed');expect(r.consumedInputCount).toBe(consumed);expect(printed(r)).toEqual([value]);});
 it('preserves typed binding and simulates all effect events',()=>{const r=run('let s:string=input("Name");sql_query(s);sql_bind("SELECT ?",42);shell(s);print(s);',['<img src=x>']);expect(r.events.map(e=>e.kind)).toEqual(['input','sql-query','sql-bind','shell','print']);expect(r.events[2]).toMatchObject({kind:'sql-bind',template:'SELECT ?',value:{type:'int',value:42},simulated:true});});
 it.each([['print(input("x"));','RUNTIME_INPUT_EXHAUSTED'],['print(1/0);','RUNTIME_DIV_ZERO'],['print(1%0);','RUNTIME_DIV_ZERO'],['print(2147483647+1);','RUNTIME_INT_OVERFLOW'],['print(50000*50000);','RUNTIME_INT_OVERFLOW'],['let n:int=-2147483647-1;print(-n);','RUNTIME_INT_OVERFLOW'],['let n:int=-2147483647-1;print(n/-1);','RUNTIME_INT_OVERFLOW']])('preserves prior output on %s', (source,code)=>{const r=run('print("before");'+source);expect(r.status).toBe('runtime-error');expect(r.diagnostics[0]!.code).toBe(code);expect(printed(r)).toEqual(['before']);});
 it('requires HALT and caps infinite instruction execution exactly',()=>{const r=run('while(true){}');expect(r.status).toBe('incomplete-limit');expect(r.diagnostics[0]!.code).toBe('LIMIT_VM_INSTRUCTIONS');expect(r.instructionCount).toBe(100000);});
 it('allows exactly 1000 events and retains them when max + 1 is attempted',()=>{const good=run('let i:int=0;while(i<1000){print(i);i=i+1;}');expect(good.status).toBe('completed');expect(good.events).toHaveLength(1000);const bad=run('let i:int=0;while(i<1001){print(i);i=i+1;}');expect(bad.status).toBe('incomplete-limit');expect(bad.events).toHaveLength(1000);expect(bad.diagnostics[0]!.code).toBe('LIMIT_VM_EVENTS');});
 it('enforces output bytes including JSON escaping before retaining an event',()=>{const r=run('let s:string=input("x");let i:int=0;while(i<100){print(s);i=i+1;}',['\n'.repeat(65536)]);expect(r.status).toBe('incomplete-limit');expect(r.diagnostics[0]!.code).toBe('LIMIT_VM_OUTPUT');expect(r.events.length).toBeGreaterThan(0);expect(Buffer.byteLength(JSON.stringify(r.events))).toBeLessThanOrEqual(1048576);});
 it('allows a 64 KiB string and rejects concatenated max + 1',()=>{const value='x'.repeat(65536);expect(run('print(input("x"));',[value]).status).toBe('completed');const r=run('let s:string=input("x");print(s+"a");',[value]);expect(r.status).toBe('incomplete-limit');expect(r.diagnostics[0]!.code).toBe('LIMIT_VM_STRING');});
 it('accounts conservatively for repeated slot references and decrements on replacement',()=>{const value='x'.repeat(65536),declarations=Array.from({length:64},(_,i)=>`let s${i}:string=s;`).join('');const r=run(`let s:string=input("x");${declarations}`,[value]);expect(r.status).toBe('incomplete-limit');expect(r.diagnostics[0]!.code).toBe('LIMIT_VM_STORAGE');const good=run('let s:string=input("x");let i:int=0;while(i<2000){s="";s="a";i=i+1;}',[value]);expect(good.status).toBe('completed');});
 it('checks deadline at the exact boundary and accepts cancellation',()=>{let ticks=0;const r=run('while(true){}',[],{nowMs:()=>ticks++?1000:0});expect(r.status).toBe('incomplete-limit');expect(r.diagnostics[0]!.code).toBe('LIMIT_VM_TIME');expect(run('print(1);',[],{nowMs:()=>0,checkpointAbort:()=>true}).status).toBe('cancelled');});
 it('reverifies bytecode and rejects malformed inputs or identity',()=>{const b=artifact([{opcode:'LOAD',operands:[0]},{opcode:'PRINT',operands:[]},{opcode:'HALT',operands:[]}]);expect(execute(b).diagnostics[0]!.code).toBe('BYTECODE_INVALID');const request={type:'execute',protocolVersion:1,requestId:'vm-1',snapshotId:b.snapshotId,revision:0,bytecode:b,inputs:[1]};expect(runBytecode(request as never,{nowMs:()=>0}).diagnostics[0]!.code).toBe('INPUTS_INVALID');request.inputs=[];request.revision=1;expect(runBytecode(request as never,{nowMs:()=>0}).diagnostics[0]!.code).toBe('BYTECODE_INVALID');});
});
