export * from './model.js';
export * from './contracts.js';
export * from './source.js';
export * from './limits.js';
export * from './diagnostics.js';

export { lex } from './lexer.js';
export { Parser, parse } from './parser.js';
export { SemanticChecker, checkSemantics } from './semantic.js';
export { Lowerer, lowerProgram } from './lower.js';
export { deriveEdges, adjacency, validateLoweredProgram } from './graph.js';
export { solveTaint } from './taint.js';
export { collectFindings } from './findings.js';
export { buildProvenance } from './provenance.js';
export { ReplayRecorder, reconstructReplay, applyReplayEvent } from './replay.js';
export { analyzeSource, type AnalysisHooks } from './analyze.js';
export { buildReport, serializeReport } from './report.js';
export { generateBytecode, disassembleBytecode } from './codegen.js';
export { verifyBytecode } from './verify.js';
export { runBytecode } from './vm.js';
