import { describe,it,expect } from 'vitest';
import { mkdtemp,readFile,writeFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { runCli } from '../src/run.js';
const command=(args:string[])=>spawnSync(process.execPath,[resolve('packages/cli/dist/main.js'),...args],{encoding:'utf8'});
describe('CLI analysis and runtime adapters',()=>{
 it('provides help/version and rejects bad or duplicated flags',()=>{expect(command(['--help']).status).toBe(0);expect(command(['--version']).stdout).toContain('FlowGuard 0.1.0');for(const args of [['--wat'],['x.fg','--trace','--trace'],['x.fg','--format'],['x.fg','--inputs','i.json'],['x.fg','--overwrite'],['x.fg','--format','xml'],['x.fg','extra.fg']])expect(command(args).status).toBe(2);});
 it('emits exact-snapshot completed reports with findings and opts into replay',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowguard-cli-'));try{const source=join(dir,'test.fg');await writeFile(source,'\uFEFFsql_query(input("x"));\r\n');const r=command([source,'--trace']);expect(r.status).toBe(1);const report=JSON.parse(r.stdout);expect(report.analysis.snapshot.source).toBe('\uFEFFsql_query(input("x"));\r\n');expect(report.analysis.artifacts.taint).toBeDefined();expect(report.analysis.artifacts.replay).toBeDefined();expect(report.analysis.artifacts.findings).toHaveLength(1);expect(JSON.parse(command([source]).stdout).analysis.artifacts.replay).toBeUndefined();expect(command([source,'--run']).status).toBe(3);}finally{await rm(dir,{recursive:true,force:true});}});
 it('maps invalid source/encoding/missing files and invalid input JSON',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowguard-cli-'));try{const source=join(dir,'test.fg'),inputs=join(dir,'inputs.json');await writeFile(source,'print(x);');const r=command([source]);expect(r.status).toBe(2);expect(JSON.parse(r.stdout).analysis.diagnostics[0].code).toBe('SEM_UNDECLARED');await writeFile(source,new Uint8Array([0xff]));expect(command([source]).stderr).toContain('FILE_ENCODING');expect(command([join(dir,'absent.fg')]).stderr).toContain('FILE_READ');await writeFile(source,'print(1);');await writeFile(inputs,'[1]');expect(command([source,'--run','--inputs',inputs]).stderr).toContain('INPUTS_INVALID');}finally{await rm(dir,{recursive:true,force:true});}});
 it('uses no-clobber output, explicit overwrite and reports output errors',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowguard-cli-'));try{const source=join(dir,'test.fg'),output=join(dir,'report.md');await writeFile(source,'print(1);');expect(command([source,'--format','markdown','--output',output]).status).toBe(0);const text=await readFile(output,'utf8');expect(text).toContain('Outcome: completed');expect(command([source,'--output',output]).stderr).toContain('OUTPUT_EXISTS');expect(await readFile(output,'utf8')).toBe(text);expect(command([source,'--output',output,'--overwrite']).status).toBe(0);expect(JSON.parse(await readFile(output,'utf8')).schemaVersion).toBe(1);expect(command([source,'--output',join(dir,'absent','report.json')]).stderr).toContain('OUTPUT_WRITE');}finally{await rm(dir,{recursive:true,force:true});}});
 it('maps stream/report operation failure to exit 3 instead of invalid options',async()=>{let message='';const status=await runCli(['examples/unsafe-query.fg'],{out:()=>{throw new Error('synthetic stream failure');},err:text=>{message+=text;}});expect(status).toBe(3);expect(message).toContain('ENGINE_INTERNAL');expect(message).not.toContain('synthetic stream failure');});
 it('runs supplied inputs and applies runtime failure precedence while retaining static results',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowguard-runtime-'));try{const inputs=join(dir,'inputs.json');await writeFile(inputs,'["Ada"]');const unsafe=command(['examples/unsafe-query.fg','--run','--inputs',inputs]);expect(unsafe.status).toBe(1);expect(JSON.parse(unsafe.stdout).execution.events[1]).toMatchObject({kind:'sql-query',simulated:true});const bound=command(['examples/bound-query.fg','--run','--inputs',inputs]);expect(bound.status).toBe(0);expect(JSON.parse(bound.stdout).execution.events[1]).toMatchObject({kind:'sql-bind',value:{type:'string',value:'Ada'}});const missing=command(['examples/unsafe-query.fg','--run']);expect(missing.status).toBe(3);const report=JSON.parse(missing.stdout);expect(report.analysis.status).toBe('completed');expect(report.analysis.artifacts.findings).toHaveLength(1);expect(report.execution.status).toBe('runtime-error');expect(command(['examples/runtime-error.fg','--run']).status).toBe(3);}finally{await rm(dir,{recursive:true,force:true});}});
 it('maps cooperative cancellation to 130 with a valid cancelled report',async()=>{let output='';expect(await runCli(['examples/unsafe-query.fg','--run'],{out:text=>{output+=text;},err:()=>{},cancelled:()=>true})).toBe(130);expect(JSON.parse(output).analysis.status).toBe('cancelled');});
 it('exports final scope values for completed and failed runtime',async()=>{const dir=await mkdtemp(join(tmpdir(),'flowguard-scope-'));try{const source=join(dir,'scope.fg');await writeFile(source,'let saved:int=7;{let local:int=9;}let pending:string=input("missing");');const failed=command([source,'--run']);expect(failed.status).toBe(3);expect(JSON.parse(failed.stdout).execution.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'saved',value:{type:'int',value:7}}]);const good=command(['examples/arithmetic-loop.fg','--run']);expect(good.status).toBe(0);const report=JSON.parse(good.stdout);expect(report.analysis.artifacts.bytecode.topLevelSymbolIds).toEqual(['sym-0']);expect(report.execution.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'i',value:{type:'int',value:3}}]);}finally{await rm(dir,{recursive:true,force:true});}});
});
