import { test,expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
test('real static graph, finding selection, replay and binding correction',async({page})=>{
 await page.goto('/test/phase2.html');await expect(page.getByTestId('static-error')).toBeEmpty();await expect(page.getByRole('button',{name:'SQL_QUERY_TEXT · 2:1',exact:true})).toBeVisible();await expect(page.locator('.react-flow__node')).toHaveCount(5);
 await page.getByRole('button',{name:'SQL_QUERY_TEXT · 2:1',exact:true}).click();await expect(page.locator('.source-selection')).not.toHaveCount(0);await expect(page.getByText('source · src-0',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Reset replay',exact:true}).click();await expect(page.getByText('Analysis update 0',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Next update',exact:true}).click();await expect(page.getByText('Analysis update 1',{exact:true})).toBeVisible();await page.getByRole('button',{name:'View final analysis',exact:true}).click();
 await page.getByRole('button',{name:'Use binding',exact:true}).click();await page.getByRole('button',{name:'Compile static modules',exact:true}).click();await expect(page.getByText('No modeled explicit-flow findings.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/SQL_QUERY_TEXT/})).toHaveCount(0);
 await page.screenshot({path:'test-results/phase-2-integration.png',fullPage:true});
});
test('fallback retains source, nodes, edges and keyboard selection',async({page})=>{await page.goto('/test/phase2.html');await page.getByRole('button',{name:'Force layout fallback (test only)',exact:true}).click();const button=page.getByRole('button',{name:'ir-0: const · line 1',exact:true});await expect(button).toBeVisible();await button.focus();await page.keyboard.press('Enter');await expect(button).toHaveAttribute('aria-pressed','true');await expect(page.getByRole('button',{name:/next → ir-1/})).toBeVisible();await expect(page.getByLabel('Test source')).toHaveValue(/input/);});
test('real worker exports completed snapshot and stale captures cannot replace it',async({page})=>{await page.goto('/test/phase2.html');await page.getByRole('button',{name:'Capture worker source',exact:true}).click();await page.getByRole('button',{name:'Start static worker',exact:true}).click();await expect(page.getByTestId('worker-status')).toHaveText('completed');await expect(page.getByTestId('worker-stages')).toHaveText('validate, lex, parse, semantic, lower, taint, findings, codegen, verify');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download worker JSON',exact:true}).click();const artifact=await download;const report=JSON.parse(await readFile((await artifact.path())!,'utf8'));expect(report.analysis.status).toBe('completed');expect(report.analysis.artifacts.taint).toBeDefined();expect(report.analysis.artifacts.findings).toHaveLength(1);expect(report.analysis.artifacts.bytecode).toBeDefined();await page.getByLabel('Test source').fill('print(2);');await page.getByRole('button',{name:'Capture worker source',exact:true}).click();await expect(page.getByTestId('worker-status')).toHaveText('stale');});
test('invalid source, large graph fallback, reduced motion and no remote calls',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await page.route('**/*',route=>new URL(route.request().url()).origin==='http://127.0.0.1:4174'?route.continue():route.abort());await page.goto('/test/phase2.html');await expect(page.getByRole('button',{name:'Play replay',exact:true})).toBeDisabled();await page.getByLabel('Test source').fill('print(undeclared);');await page.getByRole('button',{name:'Compile static modules',exact:true}).click();await expect(page.getByTestId('static-error')).toContainText('not declared');await page.getByLabel('Test source').fill(Array.from({length:110},(_,i)=>`let a${i}:int=${i};`).join('\n'));await page.getByRole('button',{name:'Compile static modules',exact:true}).click();await expect(page.getByRole('status').first()).toContainText('Large graph');await expect(page.getByRole('button',{name:'Next nodes',exact:true})).toBeEnabled();});
