import { test,expect,type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
async function edit(page:Page,source:string){await page.getByRole('textbox',{name:'Write a FlowGuard program'}).focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(source);}
async function analyze(page:Page){await page.getByRole('button',{name:'Analyze',exact:true}).click();await expect(page.getByText('Analysis: completed',{exact:true})).toBeVisible({timeout:12000});}
test('analysis cancellation is visible, retry works and edited snapshots cannot overwrite drafts',async({page})=>{
 await page.goto('/');await edit(page,Array.from({length:200},(_,i)=>`let v${i}:int=${i};`).join('\n'));await page.getByRole('button',{name:'Analyze',exact:true}).click();await page.getByRole('button',{name:'Cancel analysis',exact:true}).click();await expect(page.locator('footer')).toContainText('Analysis cancelled.');await expect(page.getByRole('button',{name:'Analyze',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'Analyze',exact:true}).click();await edit(page,'print(42);');await expect(page.getByRole('button',{name:'Run',exact:true})).toBeDisabled();await analyze(page);await expect(page.locator('footer')).toContainText('Analysis completed.');await expect(page.locator('.export-panel')).toContainText('current snapshot');
});
test('production reduced-motion manual replay, keyboard inspection and large-graph fallback',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/');await edit(page,'let text:string=input("x");sql_query(text);');await analyze(page);await expect(page.getByRole('button',{name:'Play replay',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Reset replay',exact:true}).click();await page.getByRole('button',{name:'Next update',exact:true}).click();await expect(page.locator('.replay-controls')).toContainText('Analysis update 1');await page.getByRole('button',{name:'View final analysis',exact:true}).click();await page.getByRole('tab',{name:'tokens',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.getByRole('tab',{name:'tokens',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByRole('tabpanel')).toContainText('let');
 await edit(page,Array.from({length:110},(_,i)=>`let v${i}:int=${i};`).join('\n'));await analyze(page);await expect(page.getByLabel('Search nodes')).toBeVisible();await expect(page.locator('.graph-list')).toContainText('All semantic edges retained');const first=page.locator('.graph-list article button').first();await first.focus();await page.keyboard.press('Enter');await expect(first).toHaveAttribute('aria-pressed','true');await expect(page.locator('.source-selection')).not.toHaveCount(0);await page.getByLabel('Search nodes').fill('not-a-node');await expect(page.locator('.graph-list')).toContainText('0 nodes');
});
test('previous-snapshot Markdown export keeps exact source and excludes stale runtime; reload stores nothing',async({page})=>{
 await page.goto('/');const source='print("source ``` <script>text</script>");';await edit(page,source);await analyze(page);await page.getByRole('button',{name:'Run',exact:true}).click();await expect(page.getByText('Execution: completed',{exact:true})).toBeVisible();await edit(page,'print(2);');await expect(page.locator('.export-panel')).toContainText('previous snapshot');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export Markdown',exact:true}).click();const file=await download;const markdown=await readFile((await file.path())!,'utf8');expect(markdown).toContain(source);expect(markdown).not.toContain('"events"');await expect(page.locator('script[src^="http"]')).toHaveCount(0);expect(await page.evaluate(()=>({local:localStorage.length,session:sessionStorage.length}))).toEqual({local:0,session:0});await page.reload();await expect(page.getByRole('button',{name:'Analyze',exact:true})).toBeDisabled();await expect(page.getByText('Execution: idle',{exact:true})).toBeVisible();
});
test('real replay byte cap labels truncation while final analysis stays usable',async({page})=>{
 await page.goto('/');await edit(page,Array.from({length:200},(_,i)=>`let v${i}:int=${i};`).join('\n'));await analyze(page);await expect(page.locator('.replay-controls')).toContainText('Replay truncated');await page.getByRole('button',{name:'Reset replay',exact:true}).click();await page.getByRole('button',{name:'Next update',exact:true}).click();await page.getByRole('button',{name:'View final analysis',exact:true}).click();await expect(page.locator('.replay-controls')).toContainText('Final static analysis');await expect(page.getByRole('button',{name:'Run',exact:true})).toBeEnabled();await expect(page.getByText('No modeled explicit-flow findings.',{exact:true})).toBeVisible();
});
