import { test,expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import type { Page } from '@playwright/test';
async function edit(page:Page,source:string){const editor=page.getByRole('textbox',{name:'Write a FlowGuard program'});await editor.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(source);}
async function analyze(page:Page){await page.getByRole('button',{name:'Analyze',exact:true}).click();await expect(page.getByText('Analysis: completed',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Verified bytecode',exact:true})).toBeVisible();}
async function run(page:Page){await page.getByRole('button',{name:'Run',exact:true}).click();await expect(page.getByText('Execution: completed',{exact:true})).toBeVisible();}
async function exported(page:Page){const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON',exact:true}).click();const file=await pending;return JSON.parse(await readFile((await file.path())!,'utf8'));}
test('production unsafe-to-binding analysis and explicit simulated execution',async({page})=>{
 const remote:string[]=[],errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin!=='http://127.0.0.1:4173'){remote.push(url.href);return route.abort();}return route.continue();});
 await page.goto('/');await edit(page,'let name:string=input("Name");\nsql_query(name);');await analyze(page);await page.getByRole('button',{name:'SQL_QUERY_TEXT · 2:1',exact:true}).click();await expect(page.locator('.source-selection')).not.toHaveCount(0);await page.locator('.bytecode-rows button').first().click();await expect(page.locator('.bytecode-rows button').first()).toHaveAttribute('aria-pressed','true');
 await page.getByLabel('Supplied values (JSON array of strings)').fill('["<img src=x onerror=alert(1)>"]');await run(page);const unsafe=await exported(page);expect(unsafe.analysis.artifacts.findings).toHaveLength(1);expect(unsafe.execution.events[1]).toMatchObject({kind:'sql-query',simulated:true,query:'<img src=x onerror=alert(1)>'});expect(unsafe.execution.snapshotId).toBe(unsafe.analysis.snapshot.snapshotId);await expect(page.locator('img')).toHaveCount(0);
 await edit(page,'let name:string=input("Name");\nsql_bind("SELECT ?",name);');await expect(page.getByRole('button',{name:'Run',exact:true})).toBeDisabled();await expect(page.getByRole('heading',{name:'Verified bytecode',exact:true})).toHaveCount(0);await analyze(page);await expect(page.getByText('No modeled explicit-flow findings.',{exact:true})).toBeVisible();await run(page);const bound=await exported(page);expect(bound.analysis.artifacts.findings).toEqual([]);expect(bound.execution.events[1]).toMatchObject({kind:'sql-bind',template:'SELECT ?',simulated:true,value:{type:'string',value:'<img src=x onerror=alert(1)>'}});expect(remote).toEqual([]);expect(errors).toEqual([]);await page.screenshot({path:'test-results/phase-3-binding-run.png',fullPage:true});
});
test('runtime input validation, exhaustion, prior events and correction',async({page})=>{await page.goto('/');await edit(page,'print("before");print(input("x"));');await analyze(page);const inputs=page.getByLabel('Supplied values (JSON array of strings)');await inputs.fill('[1]');await expect(page.getByRole('button',{name:'Run',exact:true})).toBeDisabled();await expect(page.locator('p[role=alert]')).toContainText('array of strings');await inputs.fill('[');await expect(page.locator('p[role=alert]')).toContainText('valid JSON');await inputs.fill('[]');await page.getByRole('button',{name:'Run',exact:true}).click();await expect(page.getByText('Execution: runtime-error',{exact:true})).toBeVisible();await expect(page.locator('p[role=alert]')).toContainText('RUNTIME_INPUT_EXHAUSTED');const failed=await exported(page);expect(failed.analysis.status).toBe('completed');expect(failed.execution.events).toHaveLength(1);await inputs.fill('["ok","unused"]');await run(page);await expect(page.getByText(/1 inputs consumed · 1 unused/)).toBeVisible();});
test('Stop, retry, instruction limits and edit during execution',async({page})=>{await page.goto('/');await edit(page,'while(true){}');await analyze(page);await page.getByRole('button',{name:'Run',exact:true}).click();await page.getByRole('button',{name:'Stop execution',exact:true}).click();await expect(page.getByText('Execution: cancelled',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Verified bytecode',exact:true})).toBeVisible();await page.getByRole('button',{name:'Run',exact:true}).click();await expect(page.getByText('Execution: incomplete-limit',{exact:true})).toBeVisible();await expect(page.locator('p[role=alert]')).toContainText(/LIMIT_VM_INSTRUCTIONS|LIMIT_VM_TIME/);await page.getByRole('button',{name:'Run',exact:true}).click();await edit(page,'print(42);');await expect(page.getByRole('button',{name:'Run',exact:true})).toBeDisabled();await expect(page.getByText('Execution: idle',{exact:true})).toBeVisible();await analyze(page);await run(page);});
test('malformed source cannot run and keyboard Analyze works',async({page})=>{await page.goto('/');await edit(page,'print(missing);');await page.keyboard.press('ControlOrMeta+Enter');await expect(page.getByText('Analysis: invalid-source',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Run',exact:true})).toBeDisabled();await expect(page.getByRole('heading',{name:'Verified bytecode',exact:true})).toHaveCount(0);await edit(page,'print(false && input("skip")=="yes");');await analyze(page);await run(page);expect((await exported(page)).execution.consumedInputCount).toBe(0);});
test('scope values survive real workers, reports and runtime failure without exposing locals',async({page})=>{await page.goto('/');await edit(page,'let first:int=1;{let local:string="private";}let last:bool=false;first=3;');await analyze(page);await run(page);let report=await exported(page);expect(report.analysis.artifacts.bytecode.topLevelSymbolIds).toEqual(['sym-0','sym-2']);expect(report.execution.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'first',value:{type:'int',value:3}},{symbolId:'sym-2',name:'last',value:{type:'bool',value:false}}]);await expect(page.locator('.runtime-panel')).toContainText('first: 3');await expect(page.locator('.runtime-panel')).toContainText('last: false');await expect(page.locator('.runtime-panel')).not.toContainText('private');await edit(page,'let saved:int=7;{let local:int=9;}let pending:string=input("x");');await analyze(page);await page.getByRole('button',{name:'Run',exact:true}).click();await expect(page.getByText('Execution: runtime-error',{exact:true})).toBeVisible();report=await exported(page);expect(report.execution.finalTopLevelValues).toEqual([{symbolId:'sym-0',name:'saved',value:{type:'int',value:7}}]);});
