import { createHash } from 'node:crypto';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { cpus,totalmem,platform,release,arch } from 'node:os';
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { analyzeSource,runBytecode,DEFAULT_LIMITS,buildReport,serializeReport } from '@flowguard/core';
export const hash=(source:string)=>createHash('sha256').update(source,'utf8').digest('hex');
export function analyze(source:string,id:string){const sha256=hash(source);return analyzeSource({type:'analyze',protocolVersion:1,requestId:id,snapshot:{source,filename:`${id}.fg`,revision:0,sha256,snapshotId:`snapshot-0-${sha256}`},options:{recordReplay:true}},{nowMs:()=>performance.now()});}
export function machine(){const files=execFileSync('git',['ls-files','--cached','--others','--exclude-standard','packages/core/src','apps/web/src','packages/cli/src','scripts','fixtures/evaluation.json','fixtures/evaluation','package-lock.json'],{encoding:'utf8'}).trim().split('\n').filter(Boolean).sort();const sourceHashes=Object.fromEntries(files.map(file=>[file,hash(readFileSync(file,'utf8'))]));return {sourceHashes,sourceTreeSha256:hash(JSON.stringify(sourceHashes)),measuredAt:new Date().toISOString(),timezone:'Asia/Kolkata',os:platform(),osRelease:release(),architecture:arch(),cpu:cpus()[0]?.model,logicalCpus:cpus().length,memoryBytes:totalmem(),node:process.version,npm:execFileSync('npm',['--version'],{encoding:'utf8'}).trim(),commit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),workingTreeChanged:execFileSync('git',['status','--porcelain'],{encoding:'utf8'}).trim().length>0,analyzerVersion:'0.1.0',languageVersion:1,bytecodeVersion:1,limits:DEFAULT_LIMITS};}
export async function evidence(name:string,value:unknown){await mkdir('docs/evidence',{recursive:true});await writeFile(`docs/evidence/${name}.json`,JSON.stringify(value,null,2)+'\n');}
export async function sampleReports(){for(const name of ['unsafe-query','bound-query','runtime-error']){const source=await readFile(`examples/${name}.fg`,'utf8'),result=analyze(source,name);if(result.status!=='completed')throw new Error(`${name}: ${result.status}`);const inputs=name==='runtime-error'?[]:['Ada'];const execution=runBytecode({type:'execute',protocolVersion:1,requestId:`run-${name}`,snapshotId:result.snapshot!.snapshotId,revision:0,bytecode:result.artifacts.bytecode!,inputs},{nowMs:()=>performance.now()});const report=buildReport(result,execution);await writeFile(`docs/evidence/${name}-report.json`,serializeReport(report,'json'));await writeFile(`docs/evidence/${name}-report.md`,serializeReport(report,'markdown'));}}
